server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: xiongxin
    password: 214wochusheng
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update